"""add_population_to_connected_realms

Revision ID: 37eec7227935
Revises: f56e1cf7de72
Create Date: 2025-02-03 23:35:45.346285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37eec7227935'
down_revision: Union[str, None] = 'f56e1cf7de72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_realms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_realms', schema=None) as batch_op:
        batch_op.drop_column('population')

    # ### end Alembic commands ###
