"""add logs column to connected realms

Revision ID: 615c8a4784e8
Revises: f56e1cf7de72
Create Date: 2024-02-04 19:51:30.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615c8a4784e8'
down_revision: Union[str, None] = 'f56e1cf7de72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_realms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_realms', schema=None) as batch_op:
        batch_op.drop_column('logs')

    # ### end Alembic commands ###
