"""Add active field and unique constraint to auctions

Revision ID: f56e1cf7de72
Revises: 5a2b81af93a8
Create Date: 2025-02-02 23:28:40.648972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56e1cf7de72'
down_revision: Union[str, None] = '5a2b81af93a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.create_unique_constraint('idx_auction_id_realm_id', ['auction_id', 'connected_realm_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_constraint('idx_auction_id_realm_id', type_='unique')

    # ### end Alembic commands ###
