[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "auction-analyzer"
version = "0.1.0"
description = "Auction Analyzer for World of Warcraft"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["src"]
